/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'J9App.Debug+AE822FA0E5597LS0' 
 * Target:  'Debug+AE822FA0E5597LS0' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"



#endif /* RTE_COMPONENTS_H */
